// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.5.3 DetailT.glb --transform -d
// Files: DetailT.glb [2.58MB] > C:\Users\andre\Downloads\DetailT-transformed.glb [2.51MB] (3%)
// */

import React, { useEffect, useState, useMemo, useRef } from "react";
import { portfolio } from "../../../portfolio.config";

import * as THREE from "three";
import { useFrame } from "@react-three/fiber";
import { useGLTFWithKTX2 } from "../utils/useGLTFWithKTX2";

import { convertMaterialsToMeshBasicMaterial } from "../utils/convertMaterial";
import { useModalStore } from "../stores/modalStore";

import About from "../../components/About/About";
import Project from "../../components/Project/Project";

export default function Model({ progressRef, ...props }) {
  const { nodes, materials } = useGLTFWithKTX2("/models/DetailT-v1.glb");
  const meshes = useRef({});
  const [hoveredMesh, setHoveredMesh] = useState(null);
  const { openModal } = useModalStore();

  const handleClick = (elementID) => {
    if (elementID === "about") {
      openModal("About me", <About />, elementID);
    } else {
      openModal(
        portfolio.projects[elementID].title,
        <Project projectID={elementID} />,
        elementID
      );
    }
  };

  convertMaterialsToMeshBasicMaterial(materials, 0);
  const [baseMaterial, brightHoveredMaterial, pulsingMaterial] = useMemo(() => {
    const base = materials["MergedBake_Baked.010"].clone();
    const hovered = base.clone();
    hovered.color = new THREE.Color(2.5, 2.5, 2.5);
    return [base, hovered, base.clone()];
  }, [materials]);

  useEffect(() => () => {
    baseMaterial.dispose();
    brightHoveredMaterial.dispose();
    pulsingMaterial.dispose();
  }, [baseMaterial, brightHoveredMaterial, pulsingMaterial]);

  useFrame(({ clock }) => {
    const progress = progressRef.current;
    const pulseColor = 1 + (Math.sin(clock.elapsedTime * 3) + 1) * .6;
    pulsingMaterial.color.setRGB(pulseColor, pulseColor, pulseColor);
    for (const [id, mesh] of Object.entries(meshes.current)) {
      if (!mesh) continue;
      const active = id === 'about' ? progress >= .55 && progress <= .65 : progress >= .32 && progress <= .43;
      mesh.material = hoveredMesh === id ? brightHoveredMaterial : active ? pulsingMaterial : baseMaterial;
    }
  });

  useEffect(() => {
    document.body.style.cursor = hoveredMesh ? "pointer" : "auto";
    return () => { document.body.style.cursor = "auto"; };
  }, [hoveredMesh]);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.detail_Baked.geometry}
        material={materials["MergedBake_Baked.010"]}
        position={[-6.46, 69.669, -1.148]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.About_Me_Pictures.geometry}
        ref={node => { meshes.current.about = node; }}
        material={baseMaterial}
        position={[-8.164, 68.036, 4.408]}
        rotation={[Math.PI / 2, 0, 0]}
        onPointerOver={() => setHoveredMesh("about")}
        onPointerOut={() => setHoveredMesh(null)}
        onClick={event => {
          if (event.delta > 5) return;
          event.stopPropagation();
          handleClick("about");
        }}
      />
      <mesh
        geometry={nodes.Project_One.geometry}
        ref={node => { meshes.current.one = node; }}
        material={baseMaterial}
        position={[-10.528, 69.422, -4.13]}
        rotation={[Math.PI / 2, 0, 0]}
        onPointerOver={() => setHoveredMesh("one")}
        onPointerOut={() => setHoveredMesh(null)}
        onClick={event => {
          if (event.delta > 5) return;
          event.stopPropagation();
          handleClick("one");
        }}
      />
      <mesh
        geometry={nodes.Project_Two.geometry}
        ref={node => { meshes.current.two = node; }}
        material={baseMaterial}
        position={[-9.532, 69.422, -4.13]}
        rotation={[Math.PI / 2, 0, 0]}
        onPointerOver={() => setHoveredMesh("two")}
        onPointerOut={() => setHoveredMesh(null)}
        onClick={event => {
          if (event.delta > 5) return;
          event.stopPropagation();
          handleClick("two");
        }}
      />
      <mesh
        geometry={nodes.Project_Three.geometry}
        ref={node => { meshes.current.three = node; }}
        material={baseMaterial}
        position={[-8.536, 69.422, -4.13]}
        rotation={[Math.PI / 2, 0, 0]}
        onPointerOver={() => setHoveredMesh("three")}
        onPointerOut={() => setHoveredMesh(null)}
        onClick={event => {
          if (event.delta > 5) return;
          event.stopPropagation();
          handleClick("three");
        }}
      />
      <mesh
        geometry={nodes.Project_Four.geometry}
        ref={node => { meshes.current.four = node; }}
        material={baseMaterial}
        position={[-7.541, 69.422, -4.13]}
        rotation={[Math.PI / 2, 0, 0]}
        onPointerOver={() => setHoveredMesh("four")}
        onPointerOut={() => setHoveredMesh(null)}
        onClick={event => {
          if (event.delta > 5) return;
          event.stopPropagation();
          handleClick("four");
        }}
      />
      <mesh
        geometry={nodes.about_me_text.geometry}
        material={materials["MergedBake_Baked.010"]}
        position={[-8.524, 68.356, 4.727]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}
